### ISSUE TITLE
Conflicting project name

### ISSUE THREAD

**Issue by stefanos82** [hellozee/cook#3]
Hey @hellozee, it seems there is another build system with the same [name](https://github.com/jachris/cook).

How about giving it another name? Does it have to be related to cooking?

**Comment by hellozee** [comment]
I just found about it a couple of weeks ago, until someone comes up with better name which goes with the system, I mean the Config File name, the Cache Folder, I am going to stick with cook.

**Comment by hellozee** [comment]
@stefanos82 I was thinking about cuisine, but need something simpler than that

**Comment by stefanos82** [comment]
How about coming up with a short, gibberish name that looks appealing?

**Comment by stefanos82** [comment]
OK, I have an interesting proposal.

In Greek, cook is μάγειρας. It comes from ancient Greek μάγειρος which comes from Indo-European languages **mag**.

Do you like it? It's short and could be used as the short form for mageiras (μάγειρας).

**Comment by hellozee** [comment]
Thats a cool name but I was thinking of something simple like `soup` . Let me see whether any build system with that name exists or not.

**Comment by stefanos82** [comment]
Run the following command inside google: soup site:github.com

**Comment by hellozee** [comment]
Okay no build system exist with that name but few other things do, can you come up with something simple to understand as well cool like `mag`. I really liked that name, it goes with the context but people will find it hard to relate.
Also I just implemented a logger, give it a run.

**Comment by stefanos82** [comment]
A project's name does not need to have any actual meaning. 

For instance, look at `etsy.com`. Here is a quote from its wikipedia page:

> Kalin said that he named the site Etsy because he "wanted a nonsense word because I wanted to build the brand from scratch. I was watching Fellini's 8 ½ and writing down what I was hearing. In Italian, you say 'etsi' a lot. It means 'oh, yes' (actually it's "eh, si"). And in Latin and French, it means 'what if.'"

We Greek also use `etsi` in the form of `έτσι` which comes from `οὕτως` which has a few meanings:
- thus
- so
- even so
- just so

Now, if you go with `mag`, you can say in a brief description that you took it from `μάσσω`'s root which is `mag`.

`Μάσσω` means I bake with my hands.

**Comment by stefanos82** [comment]
Nice. I have checked the logs.

My suggestion would be, since I did not get any errors or warnings, those two files should be empty.

There's no need to have files filled with unnecessary lines, such as 
```bash
2018-04-01 21:57:52.662620375 +0300 EEST m=+0.000685552 BUILD =================================================

==============================================================================================================
```

**Comment by hellozee** [comment]
I think I should close this for now
